name: flavor
description: An easy way to configure flavor settings and displaying flavor banner.
version: 2.0.0
repository: https://github.com/stefandevo/flutter-flavor
issue_tracker: https://github.com/stefandevo/flutter-flavor/issues
homepage: https://github.com/stefandevo/flutter-flavor

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.16.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0
